name: ngs_env
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - gatk4=4.3.0.0
  - ensembl-vep=110.0
  - bwa=0.7.17
  - samtools=1.17
  - htslib=1.17
  - picard=2.27.5
  - fastqc=0.11.9
  - multiqc=1.14
  - trimmomatic=0.39
  - bcftools=1.17
  - bedtools=2.30.0
  - tabix=1.17
  - pandas=2.2.2
  - python=3.10
  - pip
